# Generated by Django 5.2.4 on 2026-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cluster_eps',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='user',
            name='cluster_min_samples',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
