# Generated by Django 6.0.5 on 2026-06-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_pdftemplate_user_receipttext_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFTemplate',
        ),
    ]
