# Generated by Django 6.0.5 on 2026-06-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('transcript', models.TextField(blank=True, default='')),
                ('probability', models.FloatField()),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '보이스피싱 분석 내역',
                'ordering': ['-created_at'],
            },
        ),
    ]
